### ISSUE TITLE
[GCal error, UnknownHostException] How do I set up the remote calendar?

### ISSUE THREAD

**Issue by ecrazor1911** [axelor/axelor-business-suite#2109]
# Configuration

![image](https://user-images.githubusercontent.com/7604637/42221755-74648880-7ed3-11e8-90aa-db724a5a31f1.png)

# Error message

![image](https://user-images.githubusercontent.com/7604637/42221807-a4d9299e-7ed3-11e8-82ee-039ab01304a9.png)

# Console output

```plain
2018-07-03 15:09:06.275 ERROR 5852 --- [0.1-8080-exec-7] c.a.exception.service.TraceBackService   : net.fortuna.ical4j.connector.ObjectStoreException: java.net.UnknownHostException: [https://calendar.google.com/calendar/ical/...gmail_email_address.../private-...hash..../basic.ics]
        at net.fortuna.ical4j.connector.dav.AbstractDavObjectStore.connect(AbstractDavObjectStore.java:132)
        at com.axelor.apps.base.ical.ICalendarStore.connect(ICalendarStore.java:69)
        at com.axelor.apps.base.ical.ICalendarService.testConnect(ICalendarService.java:193)
        at com.axelor.apps.base.web.ICalendarController.testConnect(ICalendarController.java:99)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.axelor.meta.ActionHandler.call(ActionHandler.java:158)
        at com.axelor.meta.schema.actions.ActionMethod.evaluate(ActionMethod.java:80)
        at com.axelor.meta.schema.actions.ActionMethod.wrap(ActionMethod.java:85)
        at com.axelor.meta.schema.actions.ActionGroup.evaluate(ActionGroup.java:225)
        at com.axelor.meta.schema.actions.ActionGroup.wrap(ActionGroup.java:378)
        at com.axelor.meta.ActionHandler.execute(ActionHandler.java:379)
        at com.axelor.web.service.ActionService.execute(ActionService.java:101)
        at com.axelor.web.service.ActionService$$EnhancerByGuice$$727a49e4.CGLIB$execute$1(<generated>)
        at com.axelor.web.service.ActionService$$EnhancerByGuice$$727a49e4$$FastClassByGuice$$ed29834f.invoke(<generated>)
        at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
        at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:76)
        at com.axelor.rpc.RequestFilter.invoke(RequestFilter.java:59)
        at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:77)
        at com.axelor.rpc.ResponseInterceptor.invoke(ResponseInterceptor.java:67)
        at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:77)
        at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:55)
        at com.axelor.web.service.ActionService$$EnhancerByGuice$$727a49e4.execute(<generated>)
        at sun.reflect.GeneratedMethodAccessor401.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:294)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:248)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:235)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:398)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:205)
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:228)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:89)
        at com.axelor.db.tenants.AbstractTenantFilter.doFilter(AbstractTenantFilter.java:73)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:44)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
        at com.axelor.auth.AuthFilter.doFilterInternal(AuthFilter.java:82)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:41)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at com.axelor.app.internal.AppFilter.doFilter(AppFilter.java:94)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at com.google.inject.persist.PersistFilter.doFilter(PersistFilter.java:91)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at com.axelor.db.tenants.AbstractTenantFilter.doFilter(AbstractTenantFilter.java:73)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at com.axelor.web.servlet.CorsFilter.doFilter(CorsFilter.java:136)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.UnknownHostException: [https://calendar.google.com/calendar/ical/...gmail_email_address.../private-...hash..../basic.ics]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
        at sun.security.ssl.SSLSocketImpl.<init>(SSLSocketImpl.java:477)
        at sun.security.ssl.SSLSocketFactoryImpl.createSocket(SSLSocketFactoryImpl.java:153)
        at org.apache.commons.httpclient.protocol.SSLProtocolSocketFactory.createSocket(SSLProtocolSocketFactory.java:82)
        at org.apache.commons.httpclient.protocol.SSLProtocolSocketFactory.createSocket(SSLProtocolSocketFactory.java:127)
        at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:346)
        at net.fortuna.ical4j.connector.dav.DavClient.begin(DavClient.java:149)
        at net.fortuna.ical4j.connector.dav.AbstractDavObjectStore.connect(AbstractDavObjectStore.java:129)
        ... 88 more
```

**Comment by beuss** [comment]
Hi,
given the error I **think** you shouldn't enter neither https nor the path, only the host in URL (just a guess)

**Comment by ecrazor1911** [comment]
Hello! I tried without protocol scheme, but doesn't work. I can't define URL path.

```text
2018-07-03 14:50:47.920 ERROR 5852 --- [0.1-8080-exec-2] c.a.exception.service.TraceBackService   : net.fortuna.ical4j.connector.ObjectStoreException: net.fortuna.ical4j.connector.FailedOperationException: Principals not found at [/calendar/dav/...username?.../events/]
[...]
2018-07-03 14:59:41.924 ERROR 5852 --- [0.1-8080-exec-2] c.a.exception.service.TraceBackService   : net.fortuna.ical4j.connector.ObjectStoreException: net.fortuna.ical4j.connector.FailedOperationException: Principals not found at [/dav/...username?.../]
```

**Comment by beuss** [comment]
That's what I though, path shouldn't be defined.
Did you enable access through https://calendar.google.com/calendar/syncselect ?

**Comment by ecrazor1911** [comment]
Yes. Which a recommended configuration for GCAL?

![image](https://user-images.githubusercontent.com/7604637/42261500-c24e45d2-7f68-11e8-8b53-651ec8c40e11.png)

Current conf:

![image](https://user-images.githubusercontent.com/7604637/42261662-3ef6ead0-7f69-11e8-8ac4-4dba0c0c5b13.png)

**Comment by ecrazor1911** [comment]
https://developers.google.com/calendar/caldav/v2/guide#new_endpoint

**Comment by beuss** [comment]
Yes I saw it too, but ical4j does not seem to handle the new way.
I just tested with my own cal, everything went fine…

**Comment by ecrazor1911** [comment]
I'll try it on `wip` branch. I'm currently using `v5.0.2`.

**Comment by ecrazor1911** [comment]
Excuse me. That was the problem:

![image](https://user-images.githubusercontent.com/7604637/42270659-b4c14a36-7f81-11e8-9e44-3e958637e2fb.png)

Link: https://myaccount.google.com/security

Config:

![image](https://user-images.githubusercontent.com/7604637/42270818-100161ec-7f82-11e8-9394-2fdae9b0dd98.png)

Works on: `wip`, `v5.0.2`

Thank you!!
