### ISSUE TITLE
NullPointerException on  findDuplicateRecords

### ISSUE THREAD

**Issue by Cafeinoman** [axelor/axelor-business-suite#22]
find bug on http://demo.axelor.com/axelor-erp/#/ds/referential.root.partners/list/1 when I tried the find duplicate function. Reproducible online I think. The cause is : 
```
java.lang.NullPointerException
	at com.axelor.apps.base.web.GeneralController.findDuplicateRecords(GeneralController.java:135)
	at com.axelor.apps.base.web.GeneralController.showDuplicate(GeneralController.java:91)
```

**Comment by gdu-axelor** [comment]
https://github.com/axelor/axelor-business-suite/commit/03bb508e2b5ba4a2123b3f9b89b77c20ee809bcf
