### ISSUE TITLE
No implementation for com.axelor.apps.sale.service.SaleOrderLineService was bound.

### ISSUE THREAD

**Issue by tuanvm16** [axelor/axelor-business-suite#94]
I only want install CRM version. Here is list module I build with gradle

- axelor-admin
- axelor-base
- axelor-crm
- axelor-exception
- axelor-message
- axelor-sale
- axelor-tool

And this is my log file

Sep 15, 2016 9:14:34 AM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class com.axelor.web.AppContextListener
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for com.axelor.apps.sale.service.SaleOrderLineService was bound.
  while locating com.axelor.apps.sale.service.SaleOrderLineService
    for parameter 0 at com.axelor.apps.sale.service.SaleOrderServiceImpl.<init>(SaleOrderServiceImpl.java:78)
  at com.axelor.apps.sale.module.SaleModule.configure(SaleModule.java:40) (via modules: com.axelor.web.AppServletModule -> com.axelor.app.AppModule -> com.axelor.apps.sale.module.SaleModule)

2) No implementation for com.axelor.apps.sale.service.SaleOrderLineService was bound.
  while locating com.axelor.apps.sale.service.SaleOrderLineService
    for parameter 0 at com.axelor.apps.sale.service.SaleOrderServiceImpl.<init>(SaleOrderServiceImpl.java:78)
  while locating com.axelor.apps.sale.service.SaleOrderServiceImpl
    for field at com.axelor.apps.sale.service.OpportunitySaleOrderServiceImpl.saleOrderService(OpportunitySaleOrderServiceImpl.java:28)
  at com.axelor.apps.sale.module.SaleModule.configure(SaleModule.java:42) (via modules: com.axelor.web.AppServletModule -> com.axelor.app.AppModule -> com.axelor.apps.sale.module.SaleModule)

2 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at com.axelor.web.AppContextListener.getInjector(AppContextListener.java:82)
	at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47)
	at com.axelor.web.AppContextListener.contextInitialized(AppContextListener.java:44)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5099)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5615)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1092)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1984)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Sep 15, 2016 9:14:34 AM org.apache.catalina.core.StandardContext listenerStop
SEVERE: Exception sending context destroyed event to listener instance of class com.axelor.web.AppContextListener
java.lang.NullPointerException
	at com.axelor.web.AppContextListener.contextDestroyed(AppContextListener.java:76)
	at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:5146)
	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5810)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:224)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:159)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1092)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1984)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by gdu-axelor** [comment]
Fixed on dev branch : db5f226df8b46dcf7eef861a8d6ba7f8f8888964
